region: ${AWS_REGION}
metrics:
  - aws_namespace: AWS/WAFV2
    aws_metric_name: BlockedRequests
    aws_dimensions: [WebACL, Region, Rule]
    aws_statistics: [Sum]
    range_seconds: 300
    period_seconds: 60
    delay_seconds: 120

  - aws_namespace: AWS/WAFV2
    aws_metric_name: AllowedRequests
    aws_dimensions: [WebACL, Region, Rule]
    aws_statistics: [Sum]
    range_seconds: 300
    period_seconds: 60
    delay_seconds: 120

  - aws_namespace: AWS/Firehose
    aws_metric_name: DeliveryToS3.Success
    aws_dimensions: [DeliveryStreamName]
    aws_statistics: [Average]
    range_seconds: 300
    period_seconds: 60

  - aws_namespace: AWS/Firehose
    aws_metric_name: DeliveryToS3.DataFreshness
    aws_dimensions: [DeliveryStreamName]
    aws_statistics: [Maximum]
    range_seconds: 300
    period_seconds: 60

  - aws_namespace: AWS/Lambda
    aws_metric_name: Errors
    aws_dimensions: [FunctionName]
    aws_statistics: [Sum]
    range_seconds: 300
    period_seconds: 60

  - aws_namespace: AWS/Lambda
    aws_metric_name: Duration
    aws_dimensions: [FunctionName]
    aws_statistics: [Average, Maximum]
    range_seconds: 300
    period_seconds: 60

  - aws_namespace: AWS/Athena
    aws_metric_name: ProcessedBytes
    aws_dimensions: [WorkGroup]
    aws_statistics: [Sum]
    range_seconds: 300
    period_seconds: 60

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_5XX_Count
    aws_dimensions: [LoadBalancer]
    aws_statistics: [Sum]
    range_seconds: 300
    period_seconds: 60

  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: RequestCount
    aws_dimensions: [LoadBalancer]
    aws_statistics: [Sum]
    range_seconds: 300
    period_seconds: 60
